import type { Metadata } from "next";
import { LOG_RETENTION_DAYS } from "@/lib/assistant/conversation-log-policy";
import { siteConfig } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "Privacy",
  description: "What this site stores about you, which is not much.",
};

export default function PrivacyPage() {
  return (
    <section className="mx-auto w-full max-w-2xl px-6 pt-16 pb-24 sm:pt-20">
      <h1 className="text-3xl font-medium tracking-tight md:text-4xl">
        Privacy
      </h1>
      <div className="mt-8 space-y-6 leading-relaxed text-muted-foreground">
        <p>
          Short version: the site stores what you ask the assistant, for a
          little while, and nothing that says who you are.
        </p>

        <div>
          <h2 className="font-medium text-foreground">The assistant</h2>
          <p className="mt-2">
            When you chat with the &ldquo;Ask about Omer&rdquo; assistant, your
            questions and its answers are saved so {siteConfig.name} can see
            what people ask and improve its answers. Each conversation gets a
            random ID that resets when you reload the page. No name, email, IP
            address, or account is attached to it.
          </p>
          <p className="mt-2">
            Saved conversations are deleted automatically after{" "}
            {`${LOG_RETENTION_DAYS} days`}. Answers are generated by an AI model
            (Anthropic&apos;s Claude, via Vercel&apos;s AI Gateway), so please
            don&apos;t type anything personal or sensitive into the chat.
          </p>
        </div>

        <div>
          <h2 className="font-medium text-foreground">Analytics</h2>
          <p className="mt-2">
            The site uses Vercel Web Analytics, which counts page views without
            cookies or tracking you across sites.
          </p>
        </div>

        <div>
          <h2 className="font-medium text-foreground">Questions</h2>
          <p className="mt-2">
            Want a conversation deleted early, or have a question about any of
            this? Email{" "}
            <a
              href={`mailto:${siteConfig.email}`}
              className="font-medium text-foreground underline underline-offset-2"
            >
              {siteConfig.email}
            </a>
            .
          </p>
        </div>
      </div>
    </section>
  );
}
